"""Turn a growth run's event log into RESULTS.md. Every number here is recomputed from the raw JSONL.

    uv run python -m growth.report .manifest/runs/<run>-growth.jsonl [-o RESULTS.md]

Works on a finished run and on one still in progress (rounds so far).
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path

from harness.log import ROOT, read_events


def _pct(n: int, d: int) -> str:
    return f"{n}/{d} ({100 * n / d:.0f}%)" if d else "–"


def summarize(events: list[dict]) -> dict:
    start = next((e for e in events if e["type"] == "run.start"), {})
    end = next((e for e in events if e["type"] == "run.end"), None)
    tasks: dict[tuple, dict] = {}
    for e in events:
        if e["type"] == "task.end":
            tasks[(e["round"], e["split"], e["taskId"])] = e  # last write wins (gate re-runs)
    by_round: dict[int, dict[str, list[dict]]] = defaultdict(lambda: defaultdict(list))
    for (rnd, split, _), e in tasks.items():
        by_round[rnd][split].append(e)

    heldout = {e["round"]: e for e in events if e["type"] == "eval.heldout"}
    proposals = [e for e in events if e["type"] == "growth.proposal"]
    manifests = {e["skill"]: e for e in events if e["type"] == "warden.manifest"}
    gates = {e["routine"]: e for e in events if e["type"] == "gate.result"}
    blocks = [e for e in events if e["type"] == "warden.block"]
    teacher = [e for e in events if e["type"] == "model.call" and e.get("role") == "teacher"]
    student = [e for e in events if e["type"] == "model.call" and e.get("role") == "student"]
    return {
        "start": start, "end": end, "byRound": by_round, "heldout": heldout, "proposals": proposals,
        "manifests": manifests, "gates": gates, "blocks": blocks,
        "teacherCost": sum(e.get("costUsd") or 0 for e in teacher),
        "teacherCalls": len(teacher),
        "teacherProposeCalls": [e for e in teacher if e.get("purpose") == "propose"],
        "teacherTokens": (sum(e.get("promptTokens") or 0 for e in teacher), sum(e.get("outTokens") or 0 for e in teacher),
                          sum(e.get("cacheHitTokens") or 0 for e in teacher)),
        "studentCalls": len(student),
        "studentPromptTokens": sum(e.get("promptTokens") or 0 for e in student),
    }


def render(s: dict, run_path: Path) -> str:
    lines = ["# Results", ""]
    lines += [f"Generated by `growth/report.py` from `{run_path.relative_to(ROOT) if run_path.is_relative_to(ROOT) else run_path}` "
              "(raw event log, committed alongside). Nothing below is hand-entered.", ""]
    st = s["start"]
    lines += [f"- Student: `{st.get('student', 'qwen3.5:4b')}` on local Ollama · Teacher: DeepSeek V4.1 Flash "
              f"(API id `{st.get('teacher')}`)",
              f"- Tasks per round: train {st.get('trainTasks', '?')}, gate {st.get('gateTasks', '?')}, "
              f"held-out {st.get('heldoutTasks', '?')} (`core` profile, see `tasks/README.md`)",
              f"- Run status: {'finished' if s['end'] else 'IN PROGRESS / stopped early (no run.end)'}", ""]

    # headline: held-out by round
    lines += ["## Held-out (never seen by the teacher)", "",
              "| Round | Harness | Pass | Avg model calls / task |", "|---|---|---|---|"]
    for rnd in sorted(s["heldout"]):
        h = s["heldout"][rnd]
        tag = "baseline (plain tool loop)" if rnd == 0 else f"grown, round {rnd}"
        reused = f" (unchanged harness, reused round {h['reusedFromRound']})" if h.get("reusedFromRound") is not None else ""
        lines.append(f"| {rnd} | {tag}{reused} | {_pct(h['passed'], h['total'])} | {h['avgModelCalls']:.1f} |")
    if len(s["heldout"]) > 1:
        first, last = s["heldout"][min(s["heldout"])], s["heldout"][max(s["heldout"])]
        if first.get("avgModelCalls"):
            delta = 100 * (first["avgModelCalls"] - last["avgModelCalls"]) / first["avgModelCalls"]
            lines += ["", f"**Held-out pass: {first['passed']}/{first['total']} → {last['passed']}/{last['total']}; "
                          f"model calls per task: {first['avgModelCalls']:.1f} → {last['avgModelCalls']:.1f} ({delta:.0f}% fewer).**"
                      if delta >= 0 else
                      f"**Held-out pass: {first['passed']}/{first['total']} → {last['passed']}/{last['total']}; "
                      f"model calls per task: {first['avgModelCalls']:.1f} → {last['avgModelCalls']:.1f}.**"]
    held = [(rnd, e) for rnd in sorted(s["byRound"])
            for e in sorted(s["byRound"][rnd].get("heldout", []), key=lambda t: t["taskId"])]
    if held:
        lines += ["", "| Round | Held-out task | Result | Model calls | Seconds | Stop |", "|---|---|---|---|---|---|"]
        for rnd, e in held:
            lines.append(f"| {rnd} | `{e['taskId']}` | {'**pass**' if e['pass'] else 'fail'} | {e['modelCalls']} | "
                         f"{e['ms'] / 1000:.0f} | {e.get('stopReason') or ''} |")
    lines.append("")

    # growth timeline
    lines += ["## Growth timeline", "", "| Round | Proposed routine | Warden | Gate before → after | Regressions | Outcome |",
              "|---|---|---|---|---|---|"]
    for p in s["proposals"]:
        name = p["routine"]
        m, g = s["manifests"].get(name, {}), s["gates"].get(name, {})
        warden = f"{m.get('verdict', '–')}; network {'yes' if m.get('network') else 'no'}; write {', '.join(m.get('write') or []) or '–'}"
        gate = f"{g.get('gateBefore', '–')} → {g.get('gateAfter', '–')}" if g else "–"
        regress = ", ".join(g.get("regressions") or []) or "none"
        outcome = "**accepted**" if g.get("accepted") else f"rejected{': ' + g['rejectReason'] if g.get('rejectReason') else ''}"
        lines.append(f"| {p['round']} | `{name}` | {warden} | {gate} | {regress} | {outcome} |")
    if not s["proposals"]:
        lines.append("| – | (no proposals yet) | | | | |")
    lines += ["", "Rationales (teacher's own words):", ""]
    lines += [f"- **`{p['routine']}`** (round {p['round']}): {p.get('rationale', '').strip()}" for p in s["proposals"]]
    lines.append("")

    # per round per split
    lines += ["## Every task, every round", "", "| Round | Split | Pass | Avg model calls | Avg seconds |", "|---|---|---|---|---|"]
    for rnd in sorted(s["byRound"]):
        for split in ("train", "gate", "heldout"):
            rows = s["byRound"][rnd].get(split, [])
            if rows:
                n = len(rows)
                lines.append(f"| {rnd} | {split} | {_pct(sum(r['pass'] for r in rows), n)} | "
                             f"{sum(r['modelCalls'] for r in rows) / n:.1f} | {sum(r['ms'] for r in rows) / n / 1000:.0f} |")
    lines.append("")

    pin, pout, hit = s["teacherTokens"]
    lines += ["## Cost", "",
              f"- Teacher: {s['teacherCalls']} calls, {pin:,} prompt tokens ({hit:,} cache hits), {pout:,} output tokens, "
              f"**${s['teacherCost']:.4f} total**.",
              f"- Student: {s['studentCalls']} local calls, {s['studentPromptTokens']:,} prompt tokens, $0 (runs on the laptop).",
              f"- Warden runtime blocks during the run: {len(s['blocks'])}.", ""]
    failed_props = [e for e in s["teacherProposeCalls"] if e.get("round") not in {p["round"] for p in s["proposals"]}]
    lost = sorted({e.get("round") for e in failed_props})
    lines += ["## Honest notes", ""]
    if lost:
        lines.append(f"- Round(s) {', '.join(map(str, lost))}: the teacher's proposal was cut off twice (DeepSeek counts reasoning "
                     "tokens against the 8k output cap), so no routine was proposed; the cap is now 32k.")
    if not s["end"]:
        last_round = max(s["byRound"]) if s["byRound"] else 0
        lines.append(f"- The run was stopped by hand after round {last_round} to keep the laptop free for the live demo; "
                     "every completed round is fully logged.")
    lines += [
              "- Per-task wall clock is 240 s for both the baseline and the grown harness (SPEC said 120 s; on this "
              "8 GB M1 a plain tool loop could only make ~5 model calls in 120 s, which would have rigged the comparison).",
              "- `core` profile (3/3/3 tasks) because a full 26-task growth run does not fit an 8 GB laptop before the deadline; "
              "the full suite is generated and verified (`tasks/README.md`).",
              "- Student runs at temperature 0 but small numeric differences between runs are possible on Metal.", ""]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("run", type=Path)
    ap.add_argument("-o", "--out", type=Path)
    a = ap.parse_args(argv)
    text = render(summarize(read_events(a.run)), a.run.resolve())
    if a.out:
        a.out.write_text(text + "\n")
        print(f"wrote {a.out}")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
